- params:
    git:
      repoName: FoxOps

      branches:
        - master
        - main
        - dev*
        - bug-fix*
        - test*

      
      branchNameTemplate: "frogbot-${IMPACTED_PACKAGE}-${BRANCH_NAME_HASH}"

    .
      commitMessageTemplate: "Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"

      
      pullRequestTitleTemplate: "[🐸 Frogbot] Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"

    
      aggregateFixes: true

  
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: true  
      minSeverity: "High"
      projects:
        - installCommand: "npm install"
          workingDirs:
            - "."
          pathExclusions:
            - "*node_modules*"
            - "*.handolint*"
            - "*test*"

    # JFrog Platform parameters
    jfrogPlatform:
    jfrogProjectKey: "myprojectkey"
    watches:
      - ""
