- params:
    git:
      repoName: FoxOps

      branches:
        - master
        - main
        - dev*
        - bug-fix*
        - test*
      branchNameTemplate: "frogbot-${IMPACTED_PACKAGE}-${BRANCH_NAME_HASH}"
      commitMessageTemplate: "Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"
      pullRequestTitleTemplate: "[🐸 Frogbot] Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"
      aggregateFixes: true
    scan:
      # Frogbot displays all existing vulnerabilities, including the ones that were not added by the pull request
      includeAllVulnerabilities: true
      failOnSecurityIssues: true
      minSeverity: "High, Critical"
      projects:
        - installCommand: "npm install"
          workingDirs:
            - "."
          pathExclusions:
            - "*node_modules*"
            - "*.handolint*"
            - "*test*"

    jfrogPlatform:
    jfrogProjectKey: "myprojectkey"
    watches:
      - ""
