name: Destroy Infrastructure
on:
  # workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to production"]
    types:
      - completed
  # push:
  #   branches:
  #     - destroy*

jobs:
  Destroy:
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        working-directory: terraform/deploy
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
      - name: Download Terraform state file from S3
        run: |
          aws s3 cp s3://state-bucket-9203143-10/terraform.tfstate
      - name: Destroy Terraform resources
        run: |
          terraform init
          terraform destroy -auto-approve
