name: Deploy dev branches to nonproduction

on:
  push:
    branches:
      - dev*

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Build and run Parcel in the background
        run: |
          nohup npx parcel build src/index.html > /dev/null 2>&1 &
          echo $! > .pidfile
  Test:
    runs-on: ubuntu-latest
    needs: [Checkout, Build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
