name: Deploy dev branches to nonproduction

on:
  pull_request:
  push:
    branches:
      - dev*

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Build and run Parcel in the background
        run: |
          nohup npx parcel build src/index.html > /dev/null 2>&1 &
          echo $! > .pidfile
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install jest
        run: npm install --save-dev jest
      - name: Run  Jest test
        run: npm test

  Format:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
  Lint:
    name: Lint
    needs: [Build, Test, Format]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2
        env:
          DISABLE_ERRORS: true
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: dev*
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

  # Release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Generate Changelog
  #       run: |
  #         echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
  #         echo ${{ github.sha }} > Release.txt
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with: |
  #         Release.txt
  #         LICENSE
  #         ${{ github.workspace }}-CHANGELOG.txt
