name: Deploy dev branches to nonproduction

on:
  pull_request:
  push:
    branches:
      - dev*

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Build and run Parcel in the background
        run: |
          nohup npx parcel build src/index.html > /dev/null 2>&1 &
          echo $! > .pidfile
  Test:
    runs-on: ubuntu-latest
    needs: [Checkout, Build]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install jest
        run: npm install --save-dev jest
      - name: Run  Jest test
        run: npm test

  # Prettier:
  #   runs-on: ubuntu-latest
  #   needs: [Checkout, Build, Test]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         ref: ${{ github.head_ref }}
  #         persist-credentials: false

  #     - name: Prettify code
  #       uses: creyD/prettier_action@v4.3
  #       with:
  #         prettier_options: --write **/*.{js,md}
  #         only_changed: True
  #         # Set your custom token
  #         github_token: ${{ secrets.MY_TOKEN }}

  Format:
    runs-on: ubuntu-latest
    needs: [Checkout, Build, Test]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}

  # Release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Generate Changelog
  #       run: |
  #         echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
  #         echo ${{ github.sha }} > Release.txt
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with: |
  #         Release.txt
  #         LICENSE
  #         ${{ github.workspace }}-CHANGELOG.txt
