name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    environment: Dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["dev*", "main", "feature*", "test*", "fix*"]
    steps:
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.MY_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_REQUIREMENTS_FILE: "package.json"
