name: Test Jira flow
on:
  pull_request:
  push:
    branches:
      - dev*

jobs:
  Login:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
